receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlp/elastic:
    endpoint: "apmserver:8200"
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/elastic]
    metrics:
      receivers: [otlp]
      exporters: [otlp/elastic]
    # logs: 
    #   receivers: [otlp]
    #   exporters: [logging, otlp/elastic]
